version: '3.8'

services:
  # Aplicação Java
  java_app:
    image: openjdk:11-jre-slim
    command: java -jar sua_aplicacao.jar
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: "0.5GB"

  # Banco de Dados MySQL
  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_fake
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: "2GB"

  # Load Balancer NGINX
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - java_app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: "0.5GB"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    external:
      name: bridge