version: '3.8'

services:
  # Banco de Dados MySQL
  mysql_db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_fake
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: "2GB"

  # Aplicação Java
  java_app:
    working_dir: /usr/src/app
    volumes:
      - ./rinha-breninho.jar:/usr/src/app/rinha-breninho.jar
    image: openjdk:17-alpine
    command: java -jar /usr/src/app/rinha-breninho.jar
    depends_on:
      - mysql_db
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: "0.5GB"

  # Load Balancer NGINX
  nginx:
    image: nginx:latest
    ports:
      - "9999:999"
    depends_on:
      - mysql_db
    expose:
      - "80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: "0.5GB"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro